version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: ./bin/rails server -b 0.0.0.0
    ports:
      - "3000:3000"
    depends_on:
      - redis
    environment:
      REDIS_URL: redis://redis:6379/1
      SECRET_KEY_BASE: <%= ENV.fetch('secret_key_base') %>

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

